name: Build Image
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'      
    paths-ignore:
      - README.md
#   schedule:
#     - cron: 0 18 * * 5

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dockerhub login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build dockerfile (with push)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          IMAGE_NAME: fillpit/whistle
          IMAGE_TAG: lts-alpine
          DOCKERFILE: Dockerfile
          FILE_PATH: .
        run: |
          docker build \
          --output "type=image,push=true" \
          -t ${IMAGE_NAME}:$(date +%s) \
          -f ${DOCKERFILE} \
          ${FILE_PATH}
